-- 1
SELECT * FROM EMPLOYEES
WHERE SALARY > (
SELECT AVG(SALARY) AS AVERAGE FROM EMPLOYEES
);

-- 2
SELECT * FROM EMPLOYEES
WHERE SALARY = (
SELECT MIN(e.SALARY) FROM EMPLOYEES e, DEPARTMENTS d
WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID
AND d.DEPARTMENT_NAME = 'IT'
);

-- 3
SELECT * FROM EMPLOYEES
WHERE HIRE_DATE > ALL (
SELECT HIRE_DATE FROM EMPLOYEES
WHERE LAST_NAME = 'King'
);

-- 4
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID = ANY (
SELECT DEPARTMENT_ID FROM DEPARTMENTS d, LOCATIONS l
WHERE d.LOCATION_ID = l.LOCATION_ID
AND l.CITY = 'Seattle'
);

-- 5
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES
WHERE SALARY > ALL ( -- MAX SALARY IN DEPT 50 = 8200
SELECT SALARY FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50
); -- SELECTING > MAX(SALARY) IN DEPT 50 BETTER THAN THIS SUBQUERY

-- 6
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES
WHERE SALARY > ANY ( -- SALARY > MIN(SALARY) OF DEPT_ID 60 EMPS
SELECT SALARY FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60
);

-- 7
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES
WHERE SALARY > 10000
);

-- 8
SELECT * FROM EMPLOYEES O
WHERE SALARY > (
SELECT AVG(SALARY) FROM EMPLOYEES I
WHERE O.DEPARTMENT_ID = I.DEPARTMENT_ID
);

-- 9
SELECT * FROM EMPLOYEES O
WHERE O.SALARY = (
SELECT MAX(I.SALARY) FROM EMPLOYEES I
WHERE I.DEPARTMENT_ID = O.DEPARTMENT_ID
); -- 11 DISTINCT DEPT_IDS

-- 10
SELECT * FROM DEPARTMENTS D
WHERE ( -- EMPLOYEE COUNT OF CURR DEPT
SELECT COUNT(E.DEPARTMENT_ID) FROM EMPLOYEES E
WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID
) > ( -- AVG EMP COUNT PER DEPT
SELECT AVG(COUNT(*)) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
);

-- 11
SELECT O.JOB_ID, O.EMPLOYEE_ID, O.FIRST_NAME, O.LAST_NAME, O.SALARY 
FROM EMPLOYEES O
WHERE O.SALARY > (
SELECT AVG(SALARY) FROM EMPLOYEES I
WHERE O.JOB_ID = I.JOB_ID
);

-- 12
SELECT * FROM EMPLOYEES
WHERE (JOB_ID, SALARY) IN ( -- EMPLOYEES WITH 'Taylor' in NAME
SELECT JOB_ID, SALARY FROM EMPLOYEES
WHERE 'Taylor' IN (FIRST_NAME, LAST_NAME)
);

-- 13
SELECT * FROM EMPLOYEES
WHERE (DEPARTMENT_ID, JOB_ID) IN (
SELECT DEPARTMENT_ID, JOB_ID FROM EMPLOYEES
WHERE 'Whalen' IN (FIRST_NAME, LAST_NAME)
);

-- 14
SELECT * FROM DEPARTMENTS D
WHERE EXISTS (
SELECT 1 FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
);

-- 15
SELECT * FROM DEPARTMENTS D
WHERE NOT EXISTS (
SELECT 1 FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
);

-- 16
SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (
SELECT EMPLOYEE_ID FROM JOB_HISTORY
);

-- 17
SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN (
SELECT EMPLOYEE_ID FROM JOB_HISTORY
);

-- 18
SELECT * FROM (
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID 
FROM EMPLOYEES
ORDER BY SALARY DESC)
WHERE ROWNUM <= 3;

-- 19
SELECT DEPARTMENT_ID, AVG(SALARY) AS AVG_SALARY
FROM (
SELECT * FROM EMPLOYEES
)
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 8000;

-- 20
CREATE TABLE HIGH_PAID_EMPLOYEES AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE 1 = 0 -- COPY ONLY STRUCTURE, NO ROWS
;
    
INSERT INTO HIGH_PAID_EMPLOYEES
    (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY > (
SELECT AVG(SALARY) FROM EMPLOYEES
);

SELECT * FROM HIGH_PAID_EMPLOYEES;

-- 21
UPDATE EMPLOYEES O
SET SALARY = SALARY + (SALARY * 0.1)
WHERE SALARY < (
SELECT AVG(SALARY) FROM EMPLOYEES I 
WHERE I.DEPARTMENT_ID = O.DEPARTMENT_ID
);

-- 22
DELETE FROM EMPLOYEES
WHERE DEPARTMENT_ID = ANY (
    SELECT DEPARTMENT_ID FROM DEPARTMENTS D, LOCATIONS L
    WHERE D.LOCATION_ID = L.LOCATION_ID
    AND L.CITY = 'Toronto'
);

-- 23
SELECT * FROM EMPLOYEES
WHERE SALARY > (
    SELECT AVG(AVG_DEPT_SALARY)
    FROM (
        SELECT AVG(SALARY) AS AVG_DEPT_SALARY
        FROM EMPLOYEES
        GROUP BY DEPARTMENT_ID
        HAVING AVG(SALARY) > (
            SELECT AVG(SALARY) FROM EMPLOYEES
        )
    )
);

-- 24
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID FROM DEPARTMENTS
    WHERE LOCATION_ID IN (
        SELECT LOCATION_ID FROM LOCATIONS
        WHERE CITY IN (
            SELECT L2.CITY
            FROM EMPLOYEES E2, DEPARTMENTS D2, LOCATIONS L2
            WHERE E2.DEPARTMENT_ID = D2.DEPARTMENT_ID
              AND D2.LOCATION_ID = L2.LOCATION_ID
            GROUP BY L2.CITY
            HAVING AVG(E2.SALARY) > (
                SELECT AVG(SALARY) FROM EMPLOYEES
            )
        )
    )
);

-- 25
SELECT * FROM EMPLOYEES
WHERE SALARY >= ( -- '=' USED BCUZ ONE CANT BE GREATER THAN ONESELF
    SELECT MAX(SALARY)
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID IN (
        SELECT DEPARTMENT_ID
        FROM EMPLOYEES
        GROUP BY DEPARTMENT_ID
        HAVING COUNT(EMPLOYEE_ID) < (
            SELECT AVG(COUNT(EMPLOYEE_ID))
            FROM EMPLOYEES
            GROUP BY DEPARTMENT_ID
        )
    )
);
