-- 1
SELECT EMPLOYEE_ID, 12 * SALARY AS YEARLY_SALARY FROM EMPLOYEES;

-- 2
SELECT * FROM EMPLOYEES WHERE (SALARY * 1.1 > 5000);

-- 3
SELECT FIRST_NAME, LAST_NAME, (SALARY + (SALARY * COMMISSION_PCT)) AS TOTAL_EARNINGS FROM EMPLOYEES;

-- 4
SELECT FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME FROM EMPLOYEES;

-- 5
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'A%' OR FIRST_NAME LIKE 'J%';

-- 6
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '%son%';

-- 7
SELECT * FROM EMPLOYEES WHERE ((SALARY * 12) - (COMMISSION_PCT * SALARY)) > 50000;

-- 8
SELECT * FROM EMPLOYEES WHERE HIRE_DATE + 30  < SYSDATE;

-- 9
SELECT * FROM EMPLOYEES WHERE (SALARY / 12) BETWEEN 300 AND 700;

-- 10
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (10, 20, 30);

-- 11
SELECT DISTINCT JOB_ID FROM EMPLOYEES;

-- 12
SELECT * FROM EMPLOYEES ORDER BY LAST_NAME ASC, SALARY DESC;

-- 13
SELECT * FROM EMPLOYEES WHERE LENGTH(FIRST_NAME) > 5;

-- 14
SELECT * FROM EMPLOYEES WHERE MOD(SALARY, 1000) = 0;

-- 15
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL OR COMMISSION_PCT = 0;

-- 16
SELECT * FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'MM') = 1;

-- 17
SELECT * FROM  EMPLOYEES WHERE FIRST_NAME LIKE 'El%' AND LAST_NAME LIKE '%o';

-- 18
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 4000 AND 7000;

-- 19
SELECT * FROM EMPLOYEES WHERE (SALARY + (SALARY * COMMISSION_PCT)) > 6000 OR HIRE_DATE > DATE '2010-01-01';

-- 20
SELECT UPPER(FIRST_NAME), LOWER(LAST_NAME) FROM EMPLOYEES;

-- 21
-- HIRE_DATE doesn't have time in date by default.
SELECT * FROM EMPLOYEES WHERE HIRE_DATE < DATE '2020-01-01';

-- 22
SELECT FIRST_NAME, SUBSTR(LAST_NAME, 1, 3) FROM EMPLOYEES;

-- 23
SELECT ROUND(SALARY, -2) FROM EMPLOYEES;

-- 24
SELECT * FROM EMPLOYEES WHERE SALARY > 5000 AND DEPARTMENT_ID != 90;

-- 25
SELECT HIRE_DATE, ROUND(SYSDATE - HIRE_DATE, 0) AS DAYS_SINCE_HIRE, HIRE_DATE + 10 AS ADDED_HIRE_DATE FROM EMPLOYEES;