SELECT EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'S_%a%';

SELECT DISTINCT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, SALARY FROM EMPLOYEES
ORDER BY DEPARTMENT_ID ASC, SALARY DESC;


SELECT SUM(SALARY) AS SAL_SUM, COUNT(SALARY) AS NUMOFSALARY, AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEES;

SELECT SYS_DATE + 10 AS FUTURE FROM DUAL;