SELECT * FROM EMPLOYEES;

-- PART A

-- 1
SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES;

-- 2
SELECT AVG(SALARY) FROM EMPLOYEES;

-- 3
SELECT DEPARTMENT_ID, COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

-- 4
SELECT DEPARTMENT_ID, MAX(COMMISSION_PCT) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

-- 5
SELECT JOB_ID, MIN(SALARY) FROM EMPLOYEES GROUP BY JOB_ID;

-- 6
SELECT JOB_ID, SUM(SALARY) FROM EMPLOYEES GROUP BY JOB_ID;

-- 7
SELECT EXTRACT(YEAR FROM HIRE_DATE) AS HIRE_YEAR, COUNT(EMPLOYEE_ID) 
FROM EMPLOYEES
GROUP BY EXTRACT(YEAR FROM HIRE_DATE);

-- 8
SELECT DEPARTMENT_ID, AVG(COMMISSION_PCT) 
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING DEPARTMENT_ID > 0.1 AND AVG(COMMISSION_PCT) IS NOT NULL;

-- 9
SELECT MANAGER_ID, COUNT(EMPLOYEE_ID) 
FROM EMPLOYEES 
GROUP BY MANAGER_ID 
HAVING COUNT(EMPLOYEE_ID) > 2;

-- 10
SELECT DEPARTMENT_ID, MAX(SALARY) 
FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY) > 12000;
