-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1041
--   at:        2026-04-29 20:33:13 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE appointment (
    appt_id      INTEGER NOT NULL,
    appt_date    DATE NOT NULL,
    appt_time    TIMESTAMP NOT NULL,
    status       VARCHAR2(20) NOT NULL,
    patient_id   INTEGER NOT NULL,
    doctor_id    INTEGER NOT NULL
);

ALTER TABLE appointment
    ADD CONSTRAINT chk_appointment_status CHECK ( status IN (
        'Scheduled',
        'Completed',
        'Cancelled'
    ) );

ALTER TABLE appointment ADD CONSTRAINT appointment_pk PRIMARY KEY ( appt_id );

CREATE TABLE department (
    dept_id     INTEGER NOT NULL,
    dept_name   VARCHAR2(50) NOT NULL
);

ALTER TABLE department ADD CONSTRAINT department_pk PRIMARY KEY ( dept_id );

CREATE TABLE doctor (
    doctor_id        INTEGER NOT NULL,
    doctor_name      VARCHAR2(100) NOT NULL,
    specialization   VARCHAR2(50),
    contact_no       VARCHAR2(15),
    consult_fee      NUMBER(10,2),
    dept_id          INTEGER
);

ALTER TABLE doctor ADD CONSTRAINT doctor_pk PRIMARY KEY ( doctor_id );

CREATE TABLE patient (
    patient_id     INTEGER NOT NULL,
    patient_name   VARCHAR2(100) NOT NULL,
    gender         CHAR(1),
    age            INTEGER,
    phone          VARCHAR2(15),
    address        VARCHAR2(200)
);

ALTER TABLE patient
    ADD CONSTRAINT patient_chk_gender CHECK ( gender IN (
        'M',
        'F',
        'O'
    ) );

ALTER TABLE patient ADD CONSTRAINT patient_pk PRIMARY KEY ( patient_id );

ALTER TABLE appointment
    ADD CONSTRAINT appointment_doctor_fk FOREIGN KEY ( doctor_id )
        REFERENCES doctor ( doctor_id );

ALTER TABLE appointment
    ADD CONSTRAINT appointment_patient_fk FOREIGN KEY ( patient_id )
        REFERENCES patient ( patient_id );

ALTER TABLE doctor
    ADD CONSTRAINT doctor_department_fk FOREIGN KEY ( dept_id )
        REFERENCES department ( dept_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0



SELECT A.APPT_ID, P.PATIENT_NAME, D.DOCTOR_NAME, DP.DEPT_NAME, A.APPT_DATE FROM APPOINTMENT A
JOIN PATIENT P 
    ON A.PATIENT_ID = P.PATIENT_ID
JOIN DOCTOR D
    ON A.DOCTOR_ID = D.DOCTOR_ID
JOIN DEPARTMENT DP
    ON D.DEPT_ID = DP.DEPT_ID;
    
SELECT D.DOCTOR_ID, D.DOCTOR_NAME, D.SPECIALIZATION, D.CONSULT_FEE 
FROM DOCTOR D
JOIN DEPARTMENT DP
    ON DP.DEPT_ID = D.DEPT_ID
WHERE DP.DEPT_ID = D.DEPT_ID AND DP.DEPT_NAME = 'Cardiology';

-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1041
--   at:        2026-04-29 21:29:12 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE customer (
    customer_id     INTEGER NOT NULL,
    customer_name   VARCHAR2(100) NOT NULL,
    email           VARCHAR2(100) NOT NULL,
    phone           VARCHAR2(15),
    delivery_addr   VARCHAR2(255)
);

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customer_id );

ALTER TABLE customer ADD CONSTRAINT customer__un UNIQUE ( email );

CREATE TABLE delivery (
    delivery_id        INTEGER NOT NULL,
    order_id           INTEGER NOT NULL,
    delivery_person    VARCHAR2(100),
    delivery_contact   VARCHAR2(15),
    delivery_status    VARCHAR2(20) NOT NULL
);

ALTER TABLE delivery
    ADD CONSTRAINT chk_delivery_status CHECK ( delivery_status IN (
        'Assigned',
        'Transit',
        'Delivered'
    ) );

ALTER TABLE delivery ADD CONSTRAINT delivery_pk PRIMARY KEY ( delivery_id );

CREATE TABLE orders (
    order_id        INTEGER NOT NULL,
    order_date      DATE DEFAULT SYSDATE NOT NULL,
    total_amount    NUMBER(2,10),
    order_status    VARCHAR2(20),
    customer_id     INTEGER NOT NULL,
    restaurant_id   INTEGER NOT NULL
);

ALTER TABLE orders ADD CONSTRAINT orders_pk PRIMARY KEY ( order_id );

CREATE TABLE restaurant (
    restaurant_id     INTEGER NOT NULL,
    restaurant_name   VARCHAR2(100) NOT NULL,
    cuisine_type      VARCHAR2(50) NOT NULL,
    location          VARCHAR2(100),
    contact_no        VARCHAR2(15)
);

ALTER TABLE restaurant ADD CONSTRAINT restaurant_pk PRIMARY KEY ( restaurant_id );

ALTER TABLE delivery
    ADD CONSTRAINT delivery_orders_fk FOREIGN KEY ( order_id )
        REFERENCES orders ( order_id );

ALTER TABLE orders
    ADD CONSTRAINT orders_customer_fk FOREIGN KEY ( customer_id )
        REFERENCES customer ( customer_id );

ALTER TABLE orders
    ADD CONSTRAINT orders_restaurant_fk FOREIGN KEY ( restaurant_id )
        REFERENCES restaurant ( restaurant_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


SELECT C.CUSTOMER_NAME, R.RESTAURANT_NAME, O.TOTAL_AMOUNT, O.ORDER_STATUS 
FROM ORDERS O
JOIN CUSTOMER C
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN RESTAURANT R
    ON R.RESTAURANT_ID = O.RESTAURANT_ID
;

SELECT O.ORDER_ID, C.CUSTOMER_NAME, D.DELIVERY_PERSON FROM ORDERS O
JOIN CUSTOMER C
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN DELIVERY D
    ON O.ORDER_ID = D.ORDER_ID
WHERE D.DELIVERY_STATUS = 'Pending';


-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1041
--   at:        2026-04-29 21:53:47 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE course (
    course_id          VARCHAR2(10) NOT NULL,
    course_title       VARCHAR2(100),
    credit_hrs         INTEGER,
    semester_offered   VARCHAR2(20),
    dept_id            INTEGER NOT NULL,
    instructor_id      INTEGER NOT NULL
);

ALTER TABLE course ADD CONSTRAINT course_pk PRIMARY KEY ( course_id );

CREATE TABLE department (
    dept_id     INTEGER NOT NULL,
    dept_name   VARCHAR2(100) NOT NULL
);

ALTER TABLE department ADD CONSTRAINT department_pk PRIMARY KEY ( dept_id );

CREATE TABLE enrollment (
    enroll_id     INTEGER NOT NULL,
    enroll_date   DATE,
    semester      VARCHAR2(20),
    grade         CHAR(2),
    student_id    INTEGER NOT NULL,
    course_id     VARCHAR2(10) NOT NULL
);

ALTER TABLE enrollment ADD CONSTRAINT enrollment_pk PRIMARY KEY ( enroll_id );

CREATE TABLE instructor (
    instructor_id   INTEGER NOT NULL,
    name            VARCHAR2(100),
    email           VARCHAR2(100),
    designation     VARCHAR2(50),
    dept_id         INTEGER NOT NULL
);

ALTER TABLE instructor ADD CONSTRAINT instructor_pk PRIMARY KEY ( instructor_id );

ALTER TABLE instructor ADD CONSTRAINT instructor__un UNIQUE ( email );

CREATE TABLE student (
    student_id     INTEGER NOT NULL,
    name           VARCHAR2(100),
    email          VARCHAR2(100),
    program_name   VARCHAR2(50)
);

ALTER TABLE student ADD CONSTRAINT student_pk PRIMARY KEY ( student_id );

ALTER TABLE course
    ADD CONSTRAINT course_department_fk FOREIGN KEY ( dept_id )
        REFERENCES department ( dept_id );

ALTER TABLE course
    ADD CONSTRAINT course_instructor_fk FOREIGN KEY ( instructor_id )
        REFERENCES instructor ( instructor_id );

ALTER TABLE enrollment
    ADD CONSTRAINT enrollment_course_fk FOREIGN KEY ( course_id )
        REFERENCES course ( course_id );

ALTER TABLE enrollment
    ADD CONSTRAINT enrollment_student_fk FOREIGN KEY ( student_id )
        REFERENCES student ( student_id );

ALTER TABLE instructor
    ADD CONSTRAINT instructor_department_fk FOREIGN KEY ( dept_id )
        REFERENCES department ( dept_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SELECT S.NAME, C.COURSE_TITLE, I.NAME FROM ENROLLMENT E
JOIN STUDENT S 
    ON S.STUDENT_ID = E.STUDENT_ID
JOIN COURSE C
    ON C.COURSE_ID = E.COURSE_ID
JOIN INSTRUCTOR I
    ON I.INSTRUCTOR_ID = C.INSTRUCTOR_ID;
    
SELECT C.COURSE_TITLE, C.COURSE_TITLE, I.NAME FROM COURSE C
JOIN INSTRUCTOR I
    ON I.INSTRUCTOR_ID = C.INSTRUCTOR_ID
WHERE C.SEMESTER_OFFERED = 'Fall 2025';