-- 1
SELECT E.FIRST_NAME, E.LAST_NAME, E.MANAGER_ID, M.FIRST_NAME AS MANAGER_FIRST_NAME, M.LAST_NAME AS MANAGER_LAST_NAME 
FROM EMPLOYEES E 
LEFT JOIN EMPLOYEES M
ON M.EMPLOYEE_ID = E.MANAGER_ID;

-- 2
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.MANAGER_ID, M.FIRST_NAME AS MANAGER_FIRST_NAME, M.SALARY AS MANAGER_SALARY
FROM EMPLOYEES E 
JOIN EMPLOYEES M
ON M.EMPLOYEE_ID = E.MANAGER_ID
WHERE E.SALARY > M.SALARY;

-- 3
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.EMPLOYEE_ID IS NULL;

-- 4
SELECT E.EMPLOYEE_ID, E.HIRE_DATE, M.EMPLOYEE_ID AS MANAGER_ID, M.HIRE_DATE AS MANAAGER_HIRE FROM EMPLOYEES E
JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE E.HIRE_DATE > M.HIRE_DATE;

-- 5
SELECT E1.EMPLOYEE_ID, E1.FIRST_NAME, E1.LAST_NAME, E2.EMPLOYEE_ID, E2.FIRST_NAME, E2.LAST_NAME 
FROM EMPLOYEES E1 JOIN EMPLOYEES E2
ON E1.DEPARTMENT_ID = E2.DEPARTMENT_ID AND E1.EMPLOYEE_ID != E2.EMPLOYEE_ID;

-- 6
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME, L.CITY
FROM EMPLOYEES E
JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
;

-- 7
SELECT E1.EMPLOYEE_ID, E1.FIRST_NAME, E1.LAST_NAME, E1.DEPARTMENT_ID 
FROM EMPLOYEES E1
JOIN EMPLOYEES E2 
    ON E1.DEPARTMENT_ID = E2.DEPARTMENT_ID
    WHERE E2.FIRST_NAME = 'Steven' 
        AND E2.LAST_NAME = 'King'
        AND E1.EMPLOYEE_ID != E2.EMPLOYEE_ID
;

-- 8
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.SALARY, E.DEPARTMENT_ID 
FROM EMPLOYEES E 
JOIN (
        SELECT DEPARTMENT_ID, AVG(SALARY) AS DEPT_AVG
        FROM EMPLOYEES
        GROUP BY DEPARTMENT_ID
    ) T
    ON E.DEPARTMENT_ID = T.DEPARTMENT_ID AND E.SALARY > T.DEPT_AVG
;

-- 9
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, COALESCE(D.DEPARTMENT_NAME, 'NONE')
FROM EMPLOYEES E 
LEFT OUTER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
;

-- 10
SELECT E.EMPLOYEE_ID, E.LAST_NAME
FROM EMPLOYEES E
LEFT JOIN JOB_HISTORY J ON E.EMPLOYEE_ID = J.EMPLOYEE_ID
WHERE J.EMPLOYEE_ID IS NULL;

-- 11
SELECT JOB_ID FROM EMPLOYEES
UNION
SELECT JOB_ID FROM JOB_HISTORY;

-- 12
SELECT JOB_ID FROM EMPLOYEES
MINUS
SELECT JOB_ID FROM JOB_HISTORY;

-- 13
SELECT EMPLOYEE_ID FROM EMPLOYEES
INTERSECT
SELECT EMPLOYEE_ID FROM JOB_HISTORY;

-- 14
SELECT DEPARTMENT_ID FROM EMPLOYEES
INTERSECT
SELECT DEPARTMENT_ID FROM JOB_HISTORY;

-- 15
SELECT EMPLOYEE_ID FROM EMPLOYEES
UNION
SELECT EMPLOYEE_ID FROM JOB_HISTORY;

-- 16
SELECT EMPLOYEE_ID FROM JOB_HISTORY
MINUS
SELECT EMPLOYEE_ID FROM EMPLOYEES;

-- 17
SELECT JOB_ID FROM JOB_HISTORY
UNION ALL
SELECT JOB_ID FROM EMPLOYEES;

-- 18
SELECT DEPARTMENT_ID
FROM DEPARTMENTS
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID FROM EMPLOYEES 
    INTERSECT 
    SELECT DEPARTMENT_ID FROM JOB_HISTORY
);

-- 19
SELECT EMPLOYEE_ID FROM EMPLOYEES
MINUS
SELECT EMPLOYEE_ID FROM JOB_HISTORY;

-- 20
SELECT EMPLOYEE_ID, JOB_ID FROM EMPLOYEES
MINUS
SELECT EMPLOYEE_ID, JOB_ID FROM JOB_HISTORY;

-- 21
CREATE VIEW EMP_DEPT_SAL AS 
    SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME, D.DEPARTMENT_NAME, E.SALARY
    FROM EMPLOYEES E 
    JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
;

-- 22
CREATE VIEW HIGH_EARNERS AS
    SELECT * FROM EMPLOYEES
    WHERE SALARY > 10000
;

-- 23
CREATE VIEW HIERARCHY_REPORT AS
    SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLOYEE, M.FIRST_NAME || ' ' || M.LAST_NAME AS MANAGER
    FROM EMPLOYEES E 
    JOIN EMPLOYEES M 
        ON E.MANAGER_ID = M.EMPLOYEE_ID
;

-- 24
CREATE VIEW DEPT_SAL_SUMM AS
    SELECT DEPARTMENT_ID, AVG(SALARY) AS AVG_SAL
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
;

-- 25
CREATE VIEW EMP_DEPT_LOC_DEETS AS
    SELECT E.LAST_NAME, D.DEPARTMENT_NAME, L.CITY
    FROM EMPLOYEES E 
    JOIN DEPARTMENTS D 
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    JOIN LOCATIONS L 
        ON D.LOCATION_ID = L.LOCATION_ID
;

-- 26
CREATE VIEW SECURE_SALARY_VIEW AS
    SELECT * FROM EMPLOYEES 
    WHERE SALARY > 5000
WITH CHECK OPTION;

-- 27
CREATE VIEW JOB_HISTORY_READONLY AS
    SELECT * FROM JOB_HISTORY
WITH READ ONLY;

-- 28
CREATE VIEW UNIFIED_JOBS AS
    SELECT EMPLOYEE_ID, JOB_ID FROM EMPLOYEES
    UNION
    SELECT EMPLOYEE_ID, JOB_ID FROM JOB_HISTORY
;

-- 29
UPDATE HIGH_EARNERS 
    SET SALARY = SALARY + 500 
    WHERE EMPLOYEE_ID = 101
    -- success bcuz high_earners is a simple view based 
    -- on one table without aggregations.
;

-- 30
CREATE VIEW ABOVE_AVG_DEPT AS
    SELECT * FROM EMPLOYEES E
    WHERE SALARY > (
        SELECT AVG(SALARY) FROM EMPLOYEES 
        WHERE DEPARTMENT_ID = E.DEPARTMENT_ID
    )
;

-- 31
CREATE VIEW MANAGER_DEPT_CHECK AS
    SELECT E.LAST_NAME  AS EMP, 
        E.DEPARTMENT_ID AS EMP_DEPT, 
        M.LAST_NAME     AS MGR, 
        M.DEPARTMENT_ID AS MGR_DEPT
    FROM EMPLOYEES E JOIN EMPLOYEES M 
        ON E.MANAGER_ID = M.EMPLOYEE_ID
;

SELECT * FROM MANAGER_DEPT_CHECK 
    WHERE EMP_DEPT != MGR_DEPT;
    
-- 32
CREATE VIEW EMP_CITY_VIEW AS
    SELECT E.EMPLOYEE_ID, L.CITY FROM EMPLOYEES E 
    JOIN DEPARTMENTS D 
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    JOIN LOCATIONS L 
        ON D.LOCATION_ID = L.LOCATION_ID
;

SELECT * FROM EMP_CITY_VIEW 
WHERE CITY IN (
    SELECT CITY FROM EMP_CITY_VIEW 
    GROUP BY CITY 
    HAVING COUNT(*) > 5
);

-- 33
CREATE VIEW SAL_VS_AVG AS
    SELECT LAST_NAME, SALARY, (
        SELECT AVG(SALARY) FROM EMPLOYEES E2 
            WHERE E2.DEPARTMENT_ID = E1.DEPARTMENT_ID
        ) AS DEPT_AVG
    FROM EMPLOYEES E1
;

SELECT * FROM SAL_VS_AVG 
    WHERE SALARY > DEPT_AVG;
    
-- 34
CREATE VIEW EMP_DEPT_HISTORY AS
    SELECT EMPLOYEE_ID, DEPARTMENT_ID FROM EMPLOYEES
    UNION
    SELECT EMPLOYEE_ID, DEPARTMENT_ID FROM JOB_HISTORY
;

SELECT EMPLOYEE_ID FROM EMP_DEPT_HISTORY 
    GROUP BY EMPLOYEE_ID 
    HAVING COUNT(DEPARTMENT_ID) > 1;
    
-- 35
CREATE VIEW DEPT_COUNTS AS
    SELECT DEPARTMENT_ID, COUNT(*) AS EMP_COUNT 
    FROM EMPLOYEES 
        GROUP BY DEPARTMENT_ID
;

SELECT * FROM DEPT_COUNTS 
    WHERE EMP_COUNT > (
        SELECT AVG(COUNT(*)) FROM EMPLOYEES 
        GROUP BY DEPARTMENT_ID
    )
;

-- 36
CREATE VIEW SAL_COMPARE AS
    SELECT E.LAST_NAME AS EMP, E.SALARY AS E_SAL, M.SALARY AS M_SAL
    FROM EMPLOYEES E 
    JOIN EMPLOYEES M 
        ON E.MANAGER_ID = M.EMPLOYEE_ID
;

SELECT * FROM SAL_COMPARE 
    WHERE E_SAL > M_SAL;
    
-- 37
CREATE VIEW EMP_MGR_LOC AS
    SELECT E.LAST_NAME, L.CITY AS EMP_CITY, LM.CITY AS MGR_CITY
    FROM EMPLOYEES E 
    JOIN DEPARTMENTS D 
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    JOIN LOCATIONS L 
        ON D.LOCATION_ID = L.LOCATION_ID
    JOIN EMPLOYEES M 
        ON E.MANAGER_ID = M.EMPLOYEE_ID
    JOIN DEPARTMENTS DM 
        ON M.DEPARTMENT_ID = DM.DEPARTMENT_ID
    JOIN LOCATIONS LM 
        ON DM.LOCATION_ID = LM.LOCATION_ID
;

SELECT * FROM EMP_MGR_LOC WHERE EMP_CITY = MGR_CITY;

-- 38
CREATE VIEW ROLE_CHECK AS
    SELECT E.EMPLOYEE_ID, E.JOB_ID AS CURRENT_JOB, J.JOB_ID AS PAST_JOB
    FROM EMPLOYEES E 
    JOIN JOB_HISTORY J
        ON E.EMPLOYEE_ID = J.EMPLOYEE_ID
;

SELECT DISTINCT EMPLOYEE_ID FROM ROLE_CHECK 
    WHERE CURRENT_JOB = PAST_JOB;
    
-- 39
CREATE VIEW HIRE_DATE_COMPARE AS
    SELECT E.LAST_NAME, E.HIRE_DATE AS EMP_HIRE, M.HIRE_DATE AS MGR_HIRE
    FROM EMPLOYEES E 
    JOIN EMPLOYEES M 
        ON E.MANAGER_ID = M.EMPLOYEE_ID
;

SELECT * FROM HIRE_DATE_COMPARE 
    WHERE EMP_HIRE < MGR_HIRE;
    
-- 40
CREATE VIEW EMP_DEPT_JOB_DEETS AS
    SELECT E.EMPLOYEE_ID, E.SALARY, D.DEPARTMENT_NAME, J.JOB_TITLE
    FROM EMPLOYEES E
    JOIN DEPARTMENTS D 
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    JOIN JOBS J 
        ON E.JOB_ID = J.JOB_ID
;

UPDATE EMP_DEPT_JOB_DEETS 
    SET SALARY = 9000 
    WHERE EMPLOYEE_ID = 101;
-- Operation succeeds
-- Comparing with a primary key ensures that the data exists within
-- that table, allowing updates, on a table with keys.